# Generated by Django 3.1.2 on 2020-12-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_auto_20201127_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='halls.hall'),
        ),
    ]
